name: CCIL Scraper

on:
  schedule:
    # Every 10 minutes Mon–Fri, 3:30–12:30 UTC (9:00–18:00 IST)
    - cron: "*/10 3-12 * * 1-5"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: npm start

      - name: Upload data as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ccil-data
          path: data/
