name: scrape-ccil

on:
  schedule:
    # Every 10 minutes during 03:00–11:59 UTC (≈ 9:00–17:59 IST), Mon–Fri
    - cron: "*/10 3-11 * * 1-5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing updated files back to repo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci || npm i

      - name: Install Playwright Chromium
        run: npx playwright install --with-deps chromium

      - name: Run scraper
        run: npm run scrape

      - name: Commit & push data (docs/data -> GitHub Pages)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/
          git commit -m "data: update $(date -u +'%Y-%m-%dT%H:%M:%SZ')" || echo "no changes"
          git push
